version: '2'
services:
  valheim:
    build: .
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    env_file:
      - .env
    volumes:
      - ./gamedata/server:/app/valheim
      - ./gamedata/saves:/root/.config/unity3d/IronGate/Valheim